server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# --- PostgreSQL Neon Configuration ---
# L'URL JDBC doit inclure le sslmode=require pour Neon
spring.datasource.url = jdbc:postgresql://ep-late-sky-a8kljc25-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
spring.datasource.username = neondb_owner
spring.datasource.password = npg_e9XChy1EzZFK

# Hibernate configuration
# "update" est bien pour le dev, mais attention en production
spring.jpa.hibernate.ddl-auto = update

# Optionnel : Pour voir les requêtes SQL dans la console (utile pour débugger)
# spring.jpa.show-sql = true

# To improve the performance during development.
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.application
spring.jpa.defer-datasource-initialization = true