server.port=${PORT:8080}

logging.level.org.atmosphere=warn
spring.mustache.check-template-location=false

vaadin.launch-browser=true

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:radiology_app}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234abcD.}

#spring.jpa.hibernate.ddl-auto=update
# Pour le développement seulement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.application

# Disable session persistence to avoid deserialization errors during development
server.servlet.session.persistent=false
spring.devtools.restart.enabled=true

# Disable browser caching for development to ensure fresh content
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.max-age=0
spring.mvc.static-path-pattern=/**

# spring.datasource.url = jdbc:postgresql://ep-late-sky-a8kljc25-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
# spring.datasource.username = neondb_owner
# spring.datasource.password = npg_e9XChy1EzZFK